language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - cp ./db/server-state.json.sample ./db/server-state.json; export KNEX_TEST_TIMEOUT=30000; psql -c 'create database quoi_test;' -U postgres